### ISSUE TITLE
aiohttp 3.3.0

### ISSUE THREAD

**Issue by andrei15** [romis2012/aiosocksy#2]
When use aiosocksy for simple 'socks5://' proxy with aiohttp 3.3.0 I get the following error:

`TypeError: _create_proxy_connection() takes from 2 to 3 positional arguments but 4 were given` 

Is it possible to fix this?

**Comment by romis2012** [comment]
Please, upgrade to aiosocksy==0.1.1

**Comment by andrei15** [comment]
Thanks, aiosocksy 0.1.1 resolve this issue.
