### ISSUE TITLE
aiohttp.client_exceptions.certificate_errors no longer exists from version 3.4

### ISSUE THREAD

**Issue by albertvillanova** [romis2012/aiosocksy#4]
In connector.py, you make the import

```
from aiohttp.client_exceptions import (
    ServerFingerprintMismatch,
    certificate_errors,
    ssl_errors
```
but `certificate_errors` no longer exists from version 3.4 of aiohttp: 
https://github.com/aio-libs/aiohttp/blob/3.3/aiohttp/client_exceptions.py

**Comment by romis2012** [comment]
Fixed in version 0.1.2. Please upgrade. But it is strongly recommended to use [aiohttp-socks](https://github.com/romis2012/aiohttp-socks) in the future
